# Generated by Django 5.0.6 on 2024-06-17 15:08

import Backend.Books.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('yearOfPublication', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='El año no puede ser negativo.'), Backend.Books.validators.validateYearNotInFuture])),
                ('totalStock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='El stock total no puede ser negativo.')])),
                ('availableStock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='El stock disponible no puede ser negativo.')])),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.genre')),
            ],
        ),
    ]
