# Generated by Django 5.0.6 on 2024-06-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('sci-fi', 'Ciencia ficción'), ('action&adventure', 'Acción y aventura'), ('horror', 'Terror'), ('romance', 'Romance'), ('history', 'Historia'), ('philosophy', 'Filosofía'), ('science', 'Ciencia'), ('self-help', 'Autoayuda')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
