# Generated by Django 5.0.6 on 2024-06-19 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_book_genre_delete_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='availableStock',
        ),
        migrations.RemoveField(
            model_name='book',
            name='totalStock',
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='El stock no puede ser negativo.')]),
        ),
    ]
