# Generated by Django 5.0.6 on 2024-06-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_remove_book_availablestock_remove_book_totalstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='no-image', max_length=200),
            preserve_default=False,
        ),
    ]
