# Generated by Django 5.0.6 on 2024-06-17 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanDate', models.DateField()),
                ('cost', models.FloatField(default=0)),
                ('returnDate', models.DateField()),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('loanStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.loanstatus')),
                ('memberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Members.member')),
            ],
        ),
    ]
