# Generated by Django 5.0.6 on 2024-06-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='loanStatus',
            field=models.CharField(choices=[('inCourse', 'En curso'), ('returned', 'Devuelto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='loanDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='returnDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LoanStatus',
        ),
    ]
